services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-nextjs:latest
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    restart: unless-stopped
