"use client"

import { Button } from "@/components/ui/button"
import { getPathname, Link } from "@/i18n/navigation"
import { motion } from "motion/react"
import { useLocale, useTranslations } from "next-intl"
import Head from "next/head"

export default function NotFound() {
  const t = useTranslations("notFound")
  const locale = useLocale()
  // canonical link to avoid generating multiple 404 pages
  // since page indexing can also be generated by the user,
  // if it generates a 404 page, avoid generating multiple
  return (
    <>
      <Head>
        <title>{t("title")} | Gustavo Malaquias</title>
        <meta name="robots" content="noindex, follow" />
        <link
          rel="canonical"
          href={getPathname({ locale: locale, href: "/404" })}
        />
      </Head>
      <div className="min-h-screen bg-background flex flex-col items-center justify-center p-4">
        <div className="max-w-md w-full text-center">
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <h1 className="text-9xl font-bold font-mono text-primary">404</h1>

            <h2 className="text-2xl font-bold mt-6 mb-2">{t("title")}</h2>

            <p className="text-muted-foreground mb-8">{t("description")}</p>

            <Button asChild>
              <Link href="/">{t("backHome")}</Link>
            </Button>
          </motion.div>
        </div>
      </div>
    </>
  )
}
